const KEY='cozy-yarn-tracker-v4', $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?.()||Date.now()+''+Math.random(), day=()=>new Date().toISOString().slice(0,10);
function node(name='New part'){return{id:uid(),name,count:0,target:0,counterType:'Rows',sessions:[],timerStart:null,workDates:[],children:[]}}
function project(name='My cozy project'){return{id:uid(),name,count:0,target:100,counterType:'Rows',startDate:day(),finishedDate:'',yarnName:'',toolSize:'',notes:'',sessions:[],timerStart:null,workDates:[],activity:[],parts:[]}}
function load(){try{let x=JSON.parse(localStorage.getItem(KEY));if(x?.projects)return x}catch{}let p=project();return{activeId:p.id,projects:[p]}}
let state=load();const save=()=>localStorage.setItem(KEY,JSON.stringify(state));const active=()=>state.projects.find(x=>x.id===state.activeId)||state.projects[0];
const fmt=ms=>{let m=Math.floor(ms/60000);return m<60?m+'m':Math.floor(m/60)+'h '+m%60+'m'}, elapsed=o=>(o.sessions||[]).reduce((s,x)=>s+x.end-x.start,0)+(o.timerStart?Date.now()-o.timerStart:0);
function flat(a,out=[]){for(const n of a){out.push(n);flat(n.children||[],out)}return out}function totalNode(n){return elapsed(n)+(n.children||[]).reduce((s,c)=>s+totalNode(c),0)}function totalProject(p){return elapsed(p)+(p.parts||[]).reduce((s,n)=>s+totalNode(n),0)}
function find(a,id){for(const n of a){if(n.id===id)return n;let x=find(n.children||[],id);if(x)return x}}function progress(o){return o.target?Math.min(100,Math.round(o.count/o.target*100)):0}
function log(p,text,icon='🧶'){p.activity.unshift({at:new Date().toISOString(),text,icon});p.activity=p.activity.slice(0,400)}
function mark(o){if(!o.workDates.includes(day()))o.workDates.push(day())}
function stopAll(except){for(const p of state.projects)for(const o of [p,...flat(p.parts,[])])if(o.timerStart&&o.id!==except){let end=Date.now(),start=o.timerStart;o.sessions.push({start,end});o.timerStart=null;mark(o);log(p,'Worked '+fmt(end-start)+' on '+o.name,'⏱')}}
function toggle(o,p){if(o.timerStart){let end=Date.now(),start=o.timerStart;o.sessions.push({start,end});o.timerStart=null;mark(o);log(p,'Worked '+fmt(end-start)+' on '+o.name,'⏱')}else{stopAll(o.id);o.timerStart=Date.now();mark(o);log(p,'Started timer for '+o.name,'♡')}save();render()}
function change(o,p,d){let b=o.count;o.count=Math.max(0,o.count+d);mark(o);log(p,o.name+': '+b+' → '+o.count,'🧶');save();render()}
function renderActivity(el,a){el.innerHTML=a.length?a.map(x=>'<div class="event"><div class="event-icon">'+x.icon+'</div><div><strong>'+x.text+'</strong><br><time>'+new Date(x.at).toLocaleString()+'</time></div></div>').join(''):'<p class="muted">Your cozy journal will appear here.</p>'}
function renderParts(p,a,compact=false,d=0){return a.length?a.map(n=>'<div class="part" style="--depth:'+d+'"><div class="part-top"><span>○</span><div><div class="part-name">'+n.name+'</div><div class="part-meta">'+n.count+'/'+(n.target||'—')+' · '+fmt(totalNode(n))+' · '+new Set(n.workDates).size+' days</div><div class="progress"><i style="width:'+progress(n)+'%"></i></div></div><span class="pill">'+progress(n)+'%</span></div>'+(compact?'':'<div class="part-actions"><button class="mini" data-minus="'+n.id+'">−1</button><button class="mini pink" data-plus="'+n.id+'">＋1</button><button class="mini" data-timer="'+n.id+'">'+(n.timerStart?'Stop':'Timer')+'</button><button class="mini" data-child="'+n.id+'">＋ Sub-part</button></div>')+renderParts(p,n.children||[],compact,d+1)+'</div>').join(''):'<p class="muted">No parts yet.</p>'}
function home(){let acts=state.projects.flatMap(p=>p.activity.map(a=>({...a,project:p.name}))).sort((a,b)=>new Date(b.at)-new Date(a.at));$('#activeProjects').textContent=state.projects.filter(p=>!p.finishedDate).length;$('#projectList').innerHTML=state.projects.map(p=>'<button class="project-tile" data-open="'+p.id+'"><span class="project-emoji">🧶</span><span><strong>'+p.name+'</strong><span class="muted" style="display:block">Ready when you are</span><span class="progress"><i style="width:'+progress(p)+'%"></i></span></span><span class="pill">'+progress(p)+'%</span></button>').join('');renderActivity($('#homeActivity'),acts.slice(0,8))}
function projectRender(){let p=active();$('#projectName').value=p.name;$('#projectCount').textContent=p.count;$('#counterLabel').textContent=p.counterType+' counter';$('#progressText').textContent=p.count+' of '+p.target;$('#progressPct').textContent=progress(p)+'%';$('#projectBar').style.width=progress(p)+'%';$('#projectTotalTime').textContent=fmt(totalProject(p));$('#projectTimerBtn').textContent=p.timerStart?'Stop timer':'Start timer';$('#liveTimer').textContent=[p,...flat(p.parts,[])].find(x=>x.timerStart)?.name||'No timer running';$('#overviewParts').innerHTML=renderParts(p,p.parts,true);$('#partsTree').innerHTML=renderParts(p,p.parts,false);renderActivity($('#projectActivity'),p.activity);for(const [id,k] of [['counterType','counterType'],['target','target'],['startDate','startDate'],['finishedDate','finishedDate'],['yarnName','yarnName'],['toolSize','toolSize'],['projectNotes','notes']])$('#'+id).value=p[k]||''}
function render(){if($('#projectScreen').classList.contains('hidden'))home();else projectRender()}
function showProject(tab='overview'){$('#homeScreen').classList.add('hidden');$('#projectScreen').classList.remove('hidden');$$('.tab-panel').forEach(x=>x.classList.add('hidden'));$('#tab-'+tab).classList.remove('hidden');$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));render()}
function showHome(){$('#homeScreen').classList.remove('hidden');$('#projectScreen').classList.add('hidden');home()}
function modal(html){$('#sheet').innerHTML=html;$('#modal').classList.remove('hidden')}
document.addEventListener('click',e=>{let t=e.target.closest('button,[data-open]');if(!t)return;let p=active();if(t.id==='newProjectBtn')modal('<div class="sheet-head"><h2>New project</h2><button data-close>×</button></div><input id="newName" value="New yarn project"><button class="btn primary" id="createProject">Create</button>');else if(t.id==='createProject'){let n=project($('#newName').value);state.projects.unshift(n);state.activeId=n.id;save();$('#modal').classList.add('hidden');showProject()}else if(t.dataset.close!==undefined)$('#modal').classList.add('hidden');else if(t.dataset.open){state.activeId=t.dataset.open;save();showProject()}else if(t.id==='backBtn'||t.dataset.nav==='home')showHome();else if(t.dataset.nav==='project')showProject();else if(t.dataset.nav==='journal')showProject('journal');else if(t.classList.contains('tab'))showProject(t.dataset.tab);else if(t.id==='minusBtn')change(p,p,-1);else if(t.id==='plusBtn')change(p,p,1);else if(t.id==='plus5Btn')change(p,p,5);else if(t.id==='projectTimerBtn')toggle(p,p);else if(t.id==='quickAddPart'||t.id==='addRootPart')modal('<div class="sheet-head"><h2>Add part</h2><button data-close>×</button></div><input id="partName" value="New part"><input id="partTarget" type="number" placeholder="Target"><button class="btn primary" id="savePart">Save</button>');else if(t.id==='savePart'){let n=node($('#partName').value);n.target=+$('#partTarget').value||0;p.parts.push(n);log(p,'Added '+n.name,'✨');save();$('#modal').classList.add('hidden');render()}else if(t.dataset.child){modal('<div class="sheet-head"><h2>Add sub-part</h2><button data-close>×</button></div><input id="partName" value="New sub-part"><input id="partTarget" type="number" placeholder="Target"><button class="btn primary" id="saveChild" data-parent="'+t.dataset.child+'">Save</button>')}else if(t.id==='saveChild'){let n=node($('#partName').value);n.target=+$('#partTarget').value||0;find(p.parts,t.dataset.parent).children.push(n);log(p,'Added '+n.name,'✨');save();$('#modal').classList.add('hidden');render()}else if(t.dataset.minus)change(find(p.parts,t.dataset.minus),p,-1);else if(t.dataset.plus)change(find(p.parts,t.dataset.plus),p,1);else if(t.dataset.timer)toggle(find(p.parts,t.dataset.timer),p);else if(t.id==='clearActivity'){for(const x of state.projects)x.activity=[];save();render()}})
$('#projectName').addEventListener('change',e=>{active().name=e.target.value;save()});for(const [id,k,num] of [['counterType','counterType'],['target','target',1],['startDate','startDate'],['finishedDate','finishedDate'],['yarnName','yarnName'],['toolSize','toolSize'],['projectNotes','notes']])$('#'+id).addEventListener('change',e=>{active()[k]=num?(+e.target.value||0):e.target.value;save();render()});
render();
